# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-28 19:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LockBoxStatusModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this product', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='LockBoxName', max_length=40)),
                ('lockStatus', models.BooleanField(default=True)),
                ('desiredLockStatus', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(default='Not Specified', help_text='Purchased Item', max_length=40)),
                ('shippingNumber', models.CharField(help_text='Shipping number from Carrier', max_length=40)),
                ('shippingStatus', models.CharField(blank=True, default='Not Shipped Yet', max_length=100, null=True)),
                ('creationDate', models.DateTimeField(default=datetime.datetime(2019, 4, 28, 15, 28, 52, 806485))),
                ('expectedDeliveryDate', models.DateTimeField(blank=True, null=True)),
                ('barCode', models.CharField(blank=True, max_length=120, null=True)),
                ('pinCode', models.CharField(max_length=9)),
            ],
        ),
    ]
