# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-28 19:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippinginfomodel',
            name='barCodeReadable',
            field=models.CharField(default='slsl', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippinginfomodel',
            name='barCode',
            field=models.CharField(default='djdjdj', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippinginfomodel',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 28, 15, 36, 48, 485810)),
        ),
    ]
