# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-29 23:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_auto_20190428_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinginfomodel',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 29, 19, 33, 8, 572835)),
        ),
    ]
