# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-04 16:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_auto_20190429_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinginfomodel',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 4, 12, 0, 48, 961656)),
        ),
    ]
