# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-18 01:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_auto_20190504_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinginfomodel',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 17, 21, 15, 43, 937669)),
        ),
    ]
