# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-18 03:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_auto_20190517_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippinginfomodel',
            name='barCodeReadable',
        ),
        migrations.RemoveField(
            model_name='shippinginfomodel',
            name='pinCode',
        ),
        migrations.AlterField(
            model_name='shippinginfomodel',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 17, 23, 9, 54, 726291)),
        ),
    ]
