# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-20 01:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_auto_20190517_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinginfomodel',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 19, 21, 3, 49, 777171)),
        ),
        migrations.AlterField(
            model_name='shippinginfomodel',
            name='shippingStatus',
            field=models.CharField(blank=True, default='Shipped', max_length=100, null=True),
        ),
    ]
